export const INSERT_COMMENT_SAGA = "INSERT_COMMENT_SAGA";
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
export const UPDATE_COMMENT_SAGA = "UPDATE_COMMENT_SAGA";
export const SET_UPDATING_COMMENT = "SET_UPDATING_COMMENT";
export const RESET_UPDATING_COMMENT = "RESET_UPDATING_COMMENT";
