export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
export const EDIT_USER_SAGA = "EDIT_USER_SAGA";
export const ADD_USER_SAGA = "ADD_USER_SAGA";
